### ISSUE TITLE
Support for additional question types

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#20]
**Is your feature request related to a problem? Please describe.**
Looking ahead to question types and thinking about what response types we should integrate into the system in addition to sliding scale/likert. 

**Describe the solution you'd like**
Support for:  
- Radio button selection (ex. Yes/No, or Yes/No/Unsure)
- Single selection drop-down menus (Text entries, select one, "Select" as leading row)
- Percentage input (textbox with validation to not go below 0 or above 100%)
- (nice to have) multi-select from a list (drop down or checkbox?) 

**Describe alternatives you've considered**
N/A

**Additional context**
Thinking ahead to how to integrate questions that can generate measurable results.

**Comment by lcbdl** [comment]
There are rules to calculate the survey score based on different question type
- Rating Type:  score = rating result
- Boolean type: score = 1 when answer = NO, score = 5 when answer = YES

@robynpaton Please supply more rules for the additional question types
- YesNoUnsure
- Single selection drop-down
- Percentage
- Multi-select

**Comment by robynpaton** [comment]
Good question. Thinking about this logic and will get you an answer.

**Comment by robynpaton** [comment]
For the current Boolean, should the range be NO = 0?

I would propose for Yes/No/Unsure that we use: 
YES = 5
UNSURE = 1
NO = 0

For Single Selection Drop Down, selection = 1. 
For percentage, it will likely depend on the question - I could see us setting individual ranges for each? Not sure how to best standardize this but very open to suggestions. 
For multi-select, each selection = 1.

**Comment by lcbdl** [comment]
For the current Boolean, should the range be NO = 0?             Answer: Yes, we can do it

I would propose for Yes/No/Unsure that we use:                        Answer: Yes, we can do it.  I will use single select radio button type for Yes/No/Unsure.
YES = 5
UNSURE = 1
NO = 0

For Single Selection Drop Down, selection = 1.                     Answer: Do you mean the score = 1, whatever the user selects? score = 0, if the user selects none of them?

For percentage, it will likely depend on the question - I could see us setting individual ranges for each? Not sure how to best standardize this but very open to suggestions.                     Answer:  how about score = 5 * {the input percentage}?
For multi-select, each selection = 1.                                       Answer:  Yes, we can do it.

**Comment by robynpaton** [comment]
For yes/no/unsure - makes sense. 
For single select -- I'm not sure. Maybe it would depend on the question + the list? But yes, I would see select 0 = 0
For % I think it might also depend on the question. 
Multi-select -- sounds good! 

Some of these may be back pocket question types given the adjustments we've made to the assessment approach, but good to have them.

**Comment by lcbdl** [comment]
Summarize the final solution for scoring questions.  We will specify value for each option of answers.

1. Rating type:  Never(0), Rarely(1), Not Sure(2), Sometimes(3), Always(4).    Max score is 4.
2. Boolean type:  Yes (5), No(0). Or Yes(5), Not Sure(1), No(0).    Max score is 5.
3. Radio buttion type(single selection):  Option 1 (0), Option 2(1), Option 3(2).     Max score is 2.
4. Dropdown type(single selection): Option 1 (0), Option 2(1), Option 3(2).     Max score is 2.
5. Checkbox type(multiple selection): Option 1 (0), Option 2(1), Option 3(2).    Max score is 0 + 1 + 2 = 3.
