### ISSUE TITLE
Support for result weighting

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#21]
**Is your feature request related to a problem? Please describe.**
In order to make input results measurable, we'll need to be able to assign scoring weights to questions and responses. 

**Describe the solution you'd like**
For current state, all responses may have equal weight, but moving forward we'll want to  be able to adjust weighting in order to better represent value. 

**Describe alternatives you've considered**
N/A

**Additional context**
Can also be linked to #20

**Comment by lcbdl** [comment]
@robynpaton  It's feasible.  I will add the new weight feature later.

**Comment by lcbdl** [comment]
Done.  Here is an example of how to set weight to a question:
`
{
  "pages": [
    {
      "name": "section_one",
      "title": {
        "default": "Empower staff to deliver better services",
        "fr": "Empower staff to deliver better services(FR)"
      },
      "description": {
        "default": "Make sure that staff have access to the tools, training and technologies they need. Empower the team to make decisions throughout the design, build and operation of the service.",
        "fr": "Make sure that staff have access to the tools, training and technologies they need. Empower the team to make decisions throughout the design, build and operation of the service.(FR)"
      },
      "elements": [
        {
          "type": "rating",
          "name": "s01q001",
          "title": {
            "default": "What is your team's process for making changes to a service?",
            "fr": "What is your team's process for making changes to a service? (FR)"
          },
          "isRequired": false,
          "rateMax": 5,
          "minRateDescription": {
            "default": "Strongly Disagree",
            "fr": "Strongly Disgree(FR)"
          },
          "maxRateDescription": {
            "default": "Strongly Agree",
            "fr": "Strongly Agree(FR)"
          },
          "weight": 2
        },
`
