### ISSUE TITLE
Initial questions for Empower staff to deliver better services

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#30]
Standard:  Empower staff to deliver better services

Questions (and ratings/weightings): 

On our team, members self-organize and self-manage work through self-assigning tasks. 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Within our team we can openly discuss challenges and new ideas without fear of blame or reproach. 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Team members feel safe to challenge the status quo and propose new ideas
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We value and incorporate learning as part of our daily work
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Team members understand how their work contributes to business outcomes 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We can choose the tools we use to deliver our product, service or other outcome
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our management actively removes impediments and blockers that prevent us from delivering value 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Progress in making useful improvements to our work is slowed down by approvals
--> Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

We have access to environments to experiment with new approaches, tools, or solutions 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Team members can openly provide feedback and feel it is valued
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team treats failures as opportunities to improve and learn 
--> Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our management team directly assigns work to members of the team. 
--> Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

**Comment by lcbdl** [comment]
@robynpaton Hi Robyn, I might misunderstand the weighting.  For example below, do you mean the number 5, 3, 2, 1, 0 are weighting?  Why there is no 4?

Never (5), Rarely (3), Not sure (2), Sometimes (1), Always (0)

**Comment by robynpaton** [comment]
Updated the rating scale after our call today!

**Comment by lcbdl** [comment]
Finished the first draft of this section.  But the French version is expected.
