### ISSUE TITLE
Initial questions for Use Open Standards and Solutions

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#35]
Here are the initial sets of question for Use Open Standards. Can a respondent select "N/A" for a question that does not apply?

When searching for a new product, service or solution, our team considers open source solutions.
-  Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team prioritizes solutions that use open standards or open source solutions over other options
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Team members contribute back to the open source communities whose work we use
- N/A (do not score), Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our services are designed to be interoperable with other services.
- N/A (do not score), Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our work is highly dependent upon vendors, consultants, or closed-source proprietary software
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our service supports users on any device, from anywhere and at any time.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team makes our work openly accessible to the community through open source licenses
- N/A (do not score), Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our chosen solution does not limit our ability to share it with others (e.g. other governments, other jurisdictions, community groups, etc.)
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team is allowed to use open source solutions
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Hi @robynpaton 

Right now if the user doesn't answer a question, we consider the answer is 0.  For example the user answers the questions as below, you will see how we calculate the final score.

Question1: 0, 1, 2, 3, 4
Question2: 0, 1, 2, 3, 4 
Question3: N/A 0, 1, 2, 3, 4 

1. If the user doesn't answer any questions,  final score = n/a
2. if the user select Q1: 3, Q2: 3, the final score = (3+3+0) / (4+4+4) = 50%.  
3. if the user select Q1: 3, Q2: 3, Q3: 0 or N/A, then final score  = (3+3+0) / (4+4+4) = 50%.  

Let me know if the calculation is correct.

**Comment by robynpaton** [comment]
Yes, this makes sense.

**Comment by lcbdl** [comment]
Done
