### ISSUE TITLE
Initial questions for Design with Users

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#36]
Our team includes, or has direct access to, the expertise required to conduct ongoing user research and usability testing.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We have processes or tools in place to gather feedback, including anonymously.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team uses regular feedback from users to help design or redesign our service(s).
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team builds our service based on detailed requirements outlined in documentation.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team conducts user research before deciding how to implement the service.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We test our systems with a range of users, with varying needs, from varying locations, and from diverse backgrounds.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

User needs and feedback are considered when defining and measuring our key service metrics.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team prioritizes features or tasks based on what will provide the most value to our users.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team uses automation to anticipate and detect operational or quality issues before our users tell us.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Do you look at other government services to try and ensure consistency from a user perspective?
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done
