### ISSUE TITLE
Initial questions for Collaborate widely

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#37]
Our team is multidisciplinary, with the skills and capabilities required to fully deliver our service to users.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team is active in communities of practice, events or groups that pertain to the areas of expertise of team members.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We identify and collaborate with other teams inside or outside of our organization, including other levels of government, other governments, the public, or private sector organizations, who have done or are doing similar work.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team documents any APIs for our service using modern and common protocols and standards and provides examples of their use.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Data from performance monitoring tools is used to inform business decisions.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team relies on tickets or handoffs to manage collaboration between internal stakeholders or teams.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team connects regularly with other related teams to understand how decisions about our service impact other teams, and how decisions made by other teams   impact our own service.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done
