### ISSUE TITLE
Translation for initial questions

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#38]
Robyn to do! Placeholder issue so you're aware @lcbdl . Will add the translations later this week.

**Comment by robynpaton** [comment]
Waiting for translations to come back. ETA Wednesday.

**Comment by robynpaton** [comment]
Here are all of the translations. [Assessment Questions Translation File - Version 0.1-EN+FR.xlsx](https://github.com/canada-ca/digital-standards-self-assessment/files/8341828/Assessment.Questions.Translation.File.-.Version.0.1-EN%2BFR.xlsx)

**Comment by lcbdl** [comment]
@robynpaton Is N/A S/O in French?

**Comment by robynpaton** [comment]
according to Termium, yes, though I often see it just left as N/A as well.

**Comment by lcbdl** [comment]
Done.
