### ISSUE TITLE
Initial question for Iterate and improve frequently

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#39]
We have processes in place to prioritize and implement feedback from peers, stakeholders and end users.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

When a new or updated service or feature is being created, our team understands the minimum requirements for the system to be of value to users.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team experiments with new approaches based on team reflections, lessons learned and user feedback.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team collects metrics throughout the development and life cycle of the service in order to improve it.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

When resolving problems, our team dedicates time to identify the root cause of the issue and address it.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team inspects, adapts and automates our processes to deliver value to users faster.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has access to environments and resources to allow for rapid prototyping while initial requirements are being identified.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team embraces learning about and using new digital skills, approaches and tools to incorporate into our daily work.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team shares our work only once it has been finalized and approved.
- Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

Our team openly reviews processes and procedures to identify efficiencies.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team must wait for the project to be approved and funded before we can get access to environments to begin experimenting with solutions.
- Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

Our team fully architects the service delivery solution before starting to build.
- Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

</body>

</html>

**Comment by lcbdl** [comment]
Done
