### ISSUE TITLE
Initial questions for Build in accessibility from the start

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#40]
Our team continuously considers the lowest levels of digital skill, confidence and access as part of our service and platform design.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team understands how to make our services or products accessible.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team considers accessibility throughout the service design process.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Research and testing are conducted to ensure that our service is accessible to people of all abilities no matter how, where or when they access the service.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team conducts ongoing research with users with low-level digital literacy, people with disabilities, and people from different cultural and linguistic backgrounds or regions.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team implements automated accessibility checks for our services.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Accessibility compliance is **only** added at the end of the development cycle in order to pass compliance checks or audits.
- Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

Our team has specific standards we test against to ensure service accessibility.
- Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done!
