### ISSUE TITLE
Initial questions: Address security and privacy risks

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#43]
Our team considers security and privacy from the beginning of the service design process and as part of continuous iteration and improvement.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team ensures that security and privacy legal and policy requirements are respected while prioritizing service delivery and user experience.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Security measures are frictionless so that they do not place a burden on users.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has privacy and security knowledge and understanding as a competency within the team.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

The service has automated security checks and privacy protections, including role-based access and   audit functions along with the associated processes.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

There are procedures and processes in place to quickly respond to security or privacy breaches or   incidents.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team relies on security through obscurity, hiding services or information rather than improving the   security posture of the service.
Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

Our team engages an ATIP officer to ensure on-going compliance with applicable legislation and policy   requirements.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done
