### ISSUE TITLE
Initial Questions for Work in the open

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#49]
We regularly make all non-sensitive and non-personal data and information publicly available or, at a minimum, accessible across the Government of Canada for sharing and reuse.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team makes new code publicly available, or at a minimum, accessible across the Government of Canada for sharing and reuse.
- N/A, Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team contributes back to the public projects we borrow from.
- N/A, Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team tracks and makes public the metrics we use to measure our success.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team tracks and makes publicly available or, at a minimum, accessible across the Government of Canada, information about how often a change to our services fails (for example, the deployment or rollout of a service or feature experiences issues or complications).
- N/A, Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team makes visual displays that show what we’re working on and the status of our work; these displays are available publicly or at least throughout the Government of Canada.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team publicly documents, including examples of reuse, how others can use our service’s application programming interfaces (APIs), open data or information.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team releases results from user testing, including the rationale on when suggestions are not used (What we heard reports, for example)
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done.
