### ISSUE TITLE
Initial questions for Design ethical services

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#50]
Our team continually seeks out indicators of bias and ensures that our services are not reinforcing unintended biases.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

We continually seek out evidence of unintended consequences to the user in service design and delivery and work to mitigate these consequences for the user.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

When our team uses automated decision-making, we acknowledge, account for and mitigate possible biases in the data and algorithms.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team designs services that address cultural, linguistic, geographical, accessibility, technological, socioeconomic, or other access barriers to uptake.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has considered the impacts of decisions on the users and reduces negative outcomes .
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team uses data in a manner consistent with the purpose of its collection.
Never (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team delegates ethical assessment to a vendor or external service, without direct accountability.
Never (4), Rarely (3), Not sure (2), Sometimes (1), Always (0)

**Comment by lcbdl** [comment]
Done.
