### ISSUE TITLE
Initial question - Be Good Data Stewards

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#54]
Our team strives to leverage data to continually improve decision-making, operations or service delivery.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team identifies what data is needed to support decision-making, operations or service delivery, and reuses existing data wherever possible  before acquiring new data, in accordance with relevant legislative and policy requirements..
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team strives to identify and remove barriers to data sharing and release, where possible.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team ensures that users of our services can make corrections to their personal information.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team publishes data and information, when appropriate, on the open government portal.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team publishes data in plain language and machine-readable formats.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has clearly defined roles, responsibilities and accountabilities for the ongoing management and governance of data and information.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has frameworks and processes in place to regularly assess, maintain and improve data quality.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our service has processes in place to ensure proper management and governance of information and data before they are collected, used, shared, disclosed, retained, disposed of, archived, or declassified.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team ensures that information and data of business value are stored in systems where they can be properly managed.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team captures appropriate metadata to provide context for the information and data we create and capture, which enables their discovery and reuse by others.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has processes in place for determining the classification of data and information.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team is aware of which information and data have business value and prioritizes their management and governance.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team adopts  federal and/or international data standards
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team embeds data considerations in the design, planning, and delivery of initiatives.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team has frameworks and processes supporting the ethical collection, management, sharing, and use of data.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

Our team safeguards the privacy and security of data throughout the lifecycle.
- Never   (0), Rarely (1), Not sure (2), Sometimes (3), Always (4)

**Comment by lcbdl** [comment]
Done
