### ISSUE TITLE
Main page edits

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#56]
Grouping these assuming they can all be done in one go, but break them apart if needed: 

- Start using the Devops Tool now --> change to "Start your Digital Standards Self Assessment" (FR: Commencez votre auto-évaluation des normes numériques)

- Can we add more space above the section headers? It needs just a smidge more breathing room. See visual. for one example.
![image](https://user-images.githubusercontent.com/73707077/159542322-f7f9cc46-c7d0-4b2f-8e00-7d3e2341bf70.png)

- Take the survey --> Change to Take assessment (FR: Faire l'évaluation)
- Not sure what the DevOps tool is? --> Change to Not sure what the Digital Standards assessment tool is? (FR: Vous ne savez pas ce qu'est l'outil d'évaluation des normes numériques ?)
- Updates to timing section: 
   - About 5 minutes per section (FR: Environ 5 minutes par section)
   - Approximately 50 minutes to complete all *10* sections (only changes are to the numbers here, no FR required)

- Privacy notice -- can we delete the "Exception" section (as this was specific to the original tool)?

**Comment by lcbdl** [comment]
@robynpaton Can you also provide a French version of these change?

**Comment by robynpaton** [comment]
French added in-line.

**Comment by lcbdl** [comment]
Fixed.
