### ISSUE TITLE
Updates to self assessment question formats

### ISSUE THREAD

**Issue by robynpaton** [canada-ca/digital-standards-self-assessment#57]
Tiny tweaks to the formatting for all questions across all standards

- Can we reduce the font size of the question text? It's quite large and harder to read at that scale -- needs to go down just a point or two (are these styles as H1,2,3 or as px?). 
- View section results > change to Show results

**Comment by lcbdl** [comment]
@robynpaton Can you provde a French version of the change?

**Comment by robynpaton** [comment]
Voir les résultats

**Comment by lcbdl** [comment]
@robynpaton I reduced the font size, let me know if it is good.
